
print("----------")
print("Acun Simulator")
print("----------")
print(" ")
input("(!) Başlamak için ENTER tuşuna basın.")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("Bir gün normal bir şekilde survivor izliyorsundur...")
print("ama o da ne?")
print(" ")
input("(!) Devam etmek için ENTER tuşuna basın.")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("Acun diyor ki:")
print("Bunun için Exxen alman lazım.")
print(" ")
input("(!) Devam etmek için ENTER tuşuna basın.")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print(" ")
print("Ve bundan sonra bir daha tv8 izlemiyorsun!!!!!")
print(" ")
print("----------")
print("MUTLU SON!")
print("----------")
print(" ")
input("(!) Çıkmak için ENTER tuşuna basın.")
