import pyautogui
import time
counter = 0

print("-------------------------------------")
print("owoh yazan bot v1.4")
print("")
print("github.com/trashbin7")
print("-------------------------------------")
print("")
print("")
print("")
print("Bu bot hesapları banlatabilir, bu yüzden bir şifre girmeniz gerekir.")
input("(!) şifreyi girmek için ENTER basınız.")

enteredpass = pyautogui.password(text='Şifreyi girin.', title='Şifre lazım bana!', default='', mask='*')

if enteredpass == "owobot14":       #şifre burada yazıyor kullanabilirsiniz, fakat hesabınız banlanırsa biz suçlu değiliz.
    print("(!) Şifre doğru, bot 15 saniye içinde başlayacak.")
    print("(i) Botu durdurmak için bu sayfayı kapatın.")
    time.sleep(1)
    print("Kalan Süre: 15 saniye")
    time.sleep(1)
    print("Kalan Süre: 14 saniye")
    time.sleep(1)
    print("Kalan Süre: 13 saniye")
    time.sleep(1)
    print("Kalan Süre: 12 saniye")
    time.sleep(1)
    print("Kalan Süre: 11 saniye")
    time.sleep(1)
    print("Kalan Süre: 10 saniye")
    time.sleep(1)
    print("Kalan Süre: 9 saniye")
    time.sleep(1)
    print("Kalan Süre: 8 saniye")
    time.sleep(1)
    print("Kalan Süre: 7 saniye")
    time.sleep(1)
    print("Kalan Süre: 6 saniye")
    time.sleep(1)
    print("Kalan Süre: 5 saniye")
    time.sleep(1)
    print("Kalan Süre: 4 saniye")
    time.sleep(1)
    print("Kalan Süre: 3 saniye")
    time.sleep(1)
    print("Kalan Süre: 2 saniye")
    time.sleep(1)
    print("Kalan Süre: 1 saniye")
    time.sleep(1)
    print("(!) Bot başladı.")
    print("(i) Botu durdurmak için bu sayfayı kapatın.")
    while True:
        pyautogui.write('owo hunt', interval=0.1)
        time.sleep(1)
        pyautogui.press("Enter")
        counter = counter + 1
        print("bot " + str(counter) + " kez yazdı")
        time.sleep(20)
else:
    print("(!) Şifre yanlış!")
