print("loading...")
import random
import os
import time
user = 0
enemy = 0
time.sleep(0.1)
while user != 3 and enemy != 3:
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print("Pick one:")
    print("")
    print("1. [Rock] | 2. [Paper] | 3. [Scissors]")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    userrps = input("Enter your choice: ")
    if userrps == "1":
        userrps = "Rock"
    elif userrps == "2":
        userrps = "Paper"
    elif userrps == "3":
        userrps = "Scissors"
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print("Computer is thinking.")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.2)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print("Computer is thinking..")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.2)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print("Computer is thinking...")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")

    enemyrps = random.choice(['Rock', 'Paper', 'Scissors'])
    time.sleep(0.3)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps)
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.4)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS ")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.2)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "xxx")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "-xx")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "--x")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "---")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "x--")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "xx-")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "xxx")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "-xx")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "--x")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + "---")
    print("")
    print("Score: " + str(user) + " - " + str(enemy))
    print("-----------------------------------------------------")
    time.sleep(0.1)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("-----------------------------------------------------")
    print(userrps + " it is!")
    print("")
    print(userrps + " VS " + enemyrps)
    print("")
    print("Score: " + str(user) + " - " + str(enemy)) 
    print("-----------------------------------------------------")
    time.sleep(0.1)

    if userrps == enemyrps:
        time.sleep(0.1)
        os.system('cls' if os.name == 'nt' else 'clear')
        print("-----------------------------------------------------")
        print(userrps + " it is!")
        print("")
        print(userrps + " VS " + enemyrps)
        print("IT'S A TIE!")
        print("Score: " + str(user) + " - " + str(enemy))
        print("-----------------------------------------------------")
        time.sleep(2)

    if userrps == "Rock":
        if enemyrps == "Paper":
            time.sleep(0.1)
            os.system('cls' if os.name == 'nt' else 'clear')
            enemy = enemy + 1
            print("-----------------------------------------------------")
            print(userrps + " it is!")
            print("")
            print(userrps + " VS " + enemyrps)
            print("YOU LOSE!")
            print("Score: " + str(user) + " - " + str(enemy)) 
            print("-----------------------------------------------------")
            time.sleep(2)
        elif enemyrps == "Scissors":
            time.sleep(0.1)
            os.system('cls' if os.name == 'nt' else 'clear')
            user = user + 1
            print("-----------------------------------------------------")
            print(userrps + " it is!")
            print("")
            print(userrps + " VS " + enemyrps)
            print("YOU WIN!")
            print("Score: " + str(user) + " - " + str(enemy)) 
            print("-----------------------------------------------------")
            time.sleep(2)

    if userrps == "Paper":
        if enemyrps == "Rock":
            time.sleep(0.1)
            os.system('cls' if os.name == 'nt' else 'clear')
            user = user + 1
            print("-----------------------------------------------------")
            print(userrps + " it is!")
            print("")
            print(userrps + " VS " + enemyrps)
            print("YOU WIN!")
            print("Score: " + str(user) + " - " + str(enemy)) 
            print("-----------------------------------------------------")
            time.sleep(2)
        elif enemyrps == "Scissors":
            time.sleep(0.1)
            os.system('cls' if os.name == 'nt' else 'clear')
            enemy = enemy + 1
            print("-----------------------------------------------------")
            print(userrps + " it is!")
            print("")
            print(userrps + " VS " + enemyrps)
            print("YOU LOSE!")
            print("Score: " + str(user) + " - " + str(enemy)) 
            print("-----------------------------------------------------")
            time.sleep(2)
    if userrps == "Scissors":
        if enemyrps == "Rock":
            time.sleep(0.1)
            os.system('cls' if os.name == 'nt' else 'clear')
            enemy = enemy + 1
            print("-----------------------------------------------------")
            print(userrps + " it is!")
            print("")
            print(userrps + " VS " + enemyrps)
            print("YOU LOSE!")
            print("Score: " + str(user) + " - " + str(enemy)) 
            print("-----------------------------------------------------")
            time.sleep(2)
        elif enemyrps == "Paper":
            time.sleep(0.1)
            os.system('cls' if os.name == 'nt' else 'clear')
            user = user + 1
            print("-----------------------------------------------------")
            print(userrps + " it is!")
            print("")
            print(userrps + " VS " + enemyrps)
            print("YOU WIN!")
            print("Score: " + str(user) + " - " + str(enemy)) 
            print("-----------------------------------------------------")
            time.sleep(2)
time.sleep(1)
if user == 3:
    print("-----------------------------------------------------")
    print("YOU WON!")
    print("with the score of " + str(user) + " - " + str(enemy))
    print("")
    print("made by github.com/trashbin7")
    print("(!) press ENTER to exit") 
    print("-----------------------------------------------------")
elif enemy == 3:
    print("-----------------------------------------------------")
    print("YOU LOST")
    print("with the score of " + str(user) + " - " + str(enemy))
    print("")
    print("made by github.com/trashbin7")
    print("(!) press ENTER to exit")
    print("-----------------------------------------------------")
input("")
